In [46]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [47]:
dataset=pd.read_csv(r"C:\Users\rohit\Downloads\Skill Nexis Internship\week-1\Assignments\house_price_chandigarh_dataset.xls")

In [48]:
dataset.sample(10)

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,area,price,status,new/resale,price_negotiable,security_deposit,...,Lift(s),Full Power Backup,24 X 7 Security,Children's play area,Club House,Gymnasium,Swimming Pool,Sports Facility,Jogging Track,Landscaped Gardens
430,430,430,430,430,1737,6300000,NaN,1,1,1,...,1,1,1,1,1,1,1,1,1,0
51,51,51,51,51,3000,51000000,NaN,0,0,1,...,1,0,0,1,0,0,0,0,0,0
59,59,59,59,59,1640,6499320,NaN,0,0,1,...,0,1,0,1,1,1,1,1,0,0
720,720,720,720,720,1800,6900000,1.0,1,1,1,...,1,1,1,0,0,1,1,0,0,1
368,368,368,368,368,780,2094000,NaN,1,0,1,...,1,1,1,1,1,1,1,1,1,0
203,203,203,203,203,1098,3039000,1.0,1,1,1,...,0,0,1,0,0,0,0,0,0,0
497,497,497,497,497,1650,4500000,NaN,0,0,1,...,0,0,0,0,0,0,0,0,0,0
231,231,231,231,231,900,2750000,1.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
181,181,181,181,181,1250,2900000,NaN,1,0,1,...,0,0,0,0,0,0,0,0,0,0
705,705,705,705,705,900,2190000,NaN,1,1,1,...,0,1,1,1,0,0,0,0,1,0

In [49]:
dataset.shape[0]

1056

In [50]:
dataset.isnull().sum()

Unnamed: 0.3              0
Unnamed: 0.2              0
Unnamed: 0.1              0
Unnamed: 0                0
area                      0
price                     0
status                  846
new/resale                0
price_negotiable          0
security_deposit          0
furnished                 0
age of property           0
Lift(s)                   0
Full Power Backup         0
24 X 7 Security           0
Children's play area      0
Club House                0
Gymnasium                 0
Swimming Pool             0
Sports Facility           0
Jogging Track             0
Landscaped Gardens        0
dtype: int64

## Mean Imputation

In [51]:
mean_imputer=SimpleImputer(missing_values=np.nan,strategy="mean",fill_value="constant")

In [52]:
transformed_mean_imputation=mean_imputer.fit_transform(dataset)

In [53]:
transformed_dataset_mean_imputation=pd.DataFrame(transformed_mean_imputation,columns=dataset.columns)

In [54]:
transformed_dataset_mean_imputation.sample(10)

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,area,price,status,new/resale,price_negotiable,security_deposit,...,Lift(s),Full Power Backup,24 X 7 Security,Children's play area,Club House,Gymnasium,Swimming Pool,Sports Facility,Jogging Track,Landscaped Gardens
548,548.0,548.0,548.0,548.0,950.0,2890000.0,0.738095,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
848,848.0,848.0,848.0,848.0,970.0,1990000.0,0.738095,1.0,1.0,1.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0
828,828.0,828.0,828.0,828.0,945.0,2690000.0,0.738095,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
909,909.0,909.0,909.0,909.0,1550.0,3860000.0,1.000000,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
488,488.0,488.0,488.0,488.0,1596.0,5900000.0,1.000000,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
433,433.0,433.0,433.0,433.0,1737.0,6000000.0,0.738095,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0
798,798.0,798.0,798.0,798.0,600.0,1590000.0,0.738095,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55,55.0,55.0,55.0,55.0,1350.0,4299000.0,0.738095,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
181,181.0,181.0,181.0,181.0,1250.0,2900000.0,0.738095,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
219,219.0,219.0,219.0,219.0,1098.0,3040000.0,1.000000,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [55]:
transformed_dataset_mean_imputation.isnull().sum()

Unnamed: 0.3            0
Unnamed: 0.2            0
Unnamed: 0.1            0
Unnamed: 0              0
area                    0
price                   0
status                  0
new/resale              0
price_negotiable        0
security_deposit        0
furnished               0
age of property         0
Lift(s)                 0
Full Power Backup       0
24 X 7 Security         0
Children's play area    0
Club House              0
Gymnasium               0
Swimming Pool           0
Sports Facility         0
Jogging Track           0
Landscaped Gardens      0
dtype: int64

## Median Imputation

In [56]:
median_imputer=SimpleImputer(missing_values=np.nan,strategy="most_frequent",fill_value="constant")

In [57]:
transformed_median_imputation=median_imputer.fit_transform(dataset)

In [58]:
transformed_dataset_median_imputation=pd.DataFrame(transformed_median_imputation,columns=dataset.columns)

In [59]:
transformed_dataset_median_imputation.sample(10)

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,area,price,status,new/resale,price_negotiable,security_deposit,...,Lift(s),Full Power Backup,24 X 7 Security,Children's play area,Club House,Gymnasium,Swimming Pool,Sports Facility,Jogging Track,Landscaped Gardens
1015,1015.0,1015.0,1015.0,1015.0,2695.0,15900000.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
949,949.0,949.0,949.0,949.0,1670.0,4290000.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
994,994.0,994.0,994.0,994.0,1950.0,9650000.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
852,852.0,852.0,852.0,852.0,1400.0,3900000.0,1.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
801,801.0,801.0,801.0,801.0,1190.0,3500000.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
528,528.0,528.0,528.0,528.0,1040.0,3690000.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
550,550.0,550.0,550.0,550.0,1100.0,3590000.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1009,1009.0,1009.0,1009.0,1009.0,1120.0,2475000.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1025,1025.0,1025.0,1025.0,1025.0,1550.0,8125000.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
574,574.0,574.0,574.0,574.0,1080.0,3750000.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [60]:
transformed_dataset_median_imputation.isnull().sum()

Unnamed: 0.3            0
Unnamed: 0.2            0
Unnamed: 0.1            0
Unnamed: 0              0
area                    0
price                   0
status                  0
new/resale              0
price_negotiable        0
security_deposit        0
furnished               0
age of property         0
Lift(s)                 0
Full Power Backup       0
24 X 7 Security         0
Children's play area    0
Club House              0
Gymnasium               0
Swimming Pool           0
Sports Facility         0
Jogging Track           0
Landscaped Gardens      0
dtype: int64